name: adultech_launcher
description: "AdulTech - Launcher accesible para adultos mayores"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  installed_apps: ^1.6.0
  url_launcher: ^6.2.2
  flutter_tts: ^4.0.2
  android_intent_plus: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/adultech_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/adultech_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/adultech_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/adultech_logo.png"
